### ISSUE TITLE
Community Call 4

### ISSUE THREAD

**Issue by YazzyYaz** [celestiaorg/community-calls#4]
# Celestia Community Call 4

![Celestia_CommunityCall1](https://user-images.githubusercontent.com/9094204/206020221-ac5903d8-c5d5-4529-a2fc-938b7f8197f6.jpg)

- When: Thursday, December 15th, 2022 1:00 PM Eastern Standard Time (US and Canada) / 6 PM UTC - 60 minutes max
- Where: Celestia [Zoom](https://us06web.zoom.us/j/83029353483) (Instructions on joining found in the calendar event below)
- Calendar Event: Add to your calendar [here](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=MjdiaHBlNzl2c285NjB1YjZlcGxlaW9rYmUgY19za2JzbjIzNWszYmlzdHNoZ3RvNmw5ODYyNEBn&tmsrc=c_skbsn235k3bistshgto6l98624%40group.calendar.google.com)

## Agenda
* Mocha Testnet

_Please post all relevant proposals below that should be discussed and evaluated_

**Comment by huokoden** [comment]
lets go

**Comment by roomit-xyz** [comment]
lets go....

**Comment by 0xGolden** [comment]
awesome!

**Comment by cagdasdoner** [comment]
I was expecting a more “herbal” name after mamaki for the new network :) btw when could we test it?

**Comment by 0xGolden** [comment]
> I was expecting a more “herbal” name after mamaki for the new network :) btw when could we test it?

Mocha testnet launch will be next week, no exact dates yet.

**Comment by Ericonomic** [comment]
Cool :)
See you there

**Comment by shivya1689** [comment]
im ready

**Comment by Laedrianus** [comment]
> # Celestia Community Call 4
> ![Celestia_CommunityCall1](https://user-images.githubusercontent.com/9094204/206020221-ac5903d8-c5d5-4529-a2fc-938b7f8197f6.jpg)
> 
> * When: Thursday, December 15th, 2022 1:00 PM Eastern Standard Time (US and Canada) / 6 PM UTC - 60 minutes max
> * Where: Celestia [Zoom](https://us06web.zoom.us/j/83029353483) (Instructions on joining found in the calendar event below)
> * Calendar Event: Add to your calendar [here](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=MjdiaHBlNzl2c285NjB1YjZlcGxlaW9rYmUgY19za2JzbjIzNWszYmlzdHNoZ3RvNmw5ODYyNEBn&tmsrc=c_skbsn235k3bistshgto6l98624%40group.calendar.google.com)
> 
> ## Agenda
> * Mocha Testnet
> 
> _Please post all relevant proposals below that should be discussed and evaluated_

Thats good, all follow about Celestia. Thanks guys.

**Comment by whonion** [comment]
> > I was expecting a more “herbal” name after mamaki for the new network :) btw when could we test it?
> 
> Mocha testnet launch will be next week, no exact dates yet.

Waiting with reluctance!

**Comment by armeo** [comment]
let's go ...

**Comment by 0xDyno** [comment]
Interesting, see u in 6 days

**Comment by johnt9x** [comment]
let's go

**Comment by kii-awesome** [comment]
👀

**Comment by VineetSonkar** [comment]
All set :)

**Comment by uniqnodes** [comment]
Mocha 👀

**Comment by mayk1122** [comment]
muchas expectativas en este proyecto

**Comment by congdoan1987** [comment]
good

**Comment by samsamtrum** [comment]
i am waiting

**Comment by DrTsunamy** [comment]
lfg MOCHA

**Comment by fernandomes** [comment]
I can't wait to know more about Macha and the new features it will bring to the network.

**Comment by empera22r** [comment]
good lfg

**Comment by rysiman** [comment]
Set a reminder 👍

**Comment by bos5crypto** [comment]
Gassss  MOCHA

**Comment by Fireday777** [comment]
Nice GASS mocha

**Comment by hcytmz** [comment]
B)

**Comment by eanisei** [comment]
Looking forward!

**Comment by carot0089** [comment]
how wonderful ! i hope it's good

**Comment by Bhukita** [comment]
Lets go
